### PR TITLE
Pretty print JSON

### PR DESCRIPTION
**Pull request by acidghost**
Adds the .json style able to print in colours a JSON string.

It's still a WIP because I want to add the ability for the user to register his own color preferences for the .json style.

What do you think @icodeforlove?

### CODE REVIEW

**Comment by icodeforlove** [comment]
I really like this idea.

Can you add some information to README

I tested locally, and it worked fine ;)

```js
var object = {a: 1, b: new Date(), c: "1", d: {a: "{a: 1}"}};
console.log('object1: ' + JSON.stringify(object, null, '\t').json + ', object2: ' + JSON.stringify(object, null, '\t').json);
```

**Comment by acidghost** [comment]
@icodeforlove I updated the README

**Comment by icodeforlove** [comment]
@acidghost can you also bump the bower version. Also I'm ready to merge when you give me the work. It looks good.

**Comment by acidghost** [comment]
@icodeforlove I added grunt bump task and bumped version v0.0.2

**Pull request merged**
